name: query-service Checks

on:
  pull_request:
    branches:
      - develop
      - main
      - release/v*

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Checkout code
        uses: actions/checkout@v4

      # todo: add check that `go fmt` generates no diff
      # todo: add check that linter throws no warnings

      - name: Run tests
        run: go test ./pkg/query-service/...
