name: Cypress e2e tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: run cypress e2e tests
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run cypress:run
          working-directory: frontend
          env: 
            CYPRESS_baseUrl: http://localhost:8080
