name: Jest Coverage

on:
  pull_request:
    branches:
      - develop
      - main
      - release/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get base branch name
        id: base_branch
        run: echo "::set-output name=branch::${{ github.base_ref }}"

      - run: |
          git checkout -b ${{ steps.base_branch.outputs.branch }} origin/${{ steps.base_branch.outputs.branch }}
          git checkout -

      - name: Install dependencies
        run: cd frontend && yarn install

      - name: Jest
        run: cd frontend && npm run i18n:generate-hash && npm run test
