name: Jest Coverage - changed files

on:
  pull_request:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: cd frontend && npm install -g yarn && yarn

      # - name: npm run test:changedsince
      #   run: cd frontend && npm run i18n:generate-hash && npm run test:changedsince

      - name: run coverage
        run: cd frontend && npx jest --coverage --silent --changedSince=origin/develop --passWithNoTests
