name: Jest Coverage - changed files

on:
  pull_request:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set the remote origin using the repository URL
      - name: Set remote origin
        run: git remote add origin https://github.com/SigNoz/signoz

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: cd frontend && npm install -g yarn && yarn

      - name: npm run test:changedsince
        run: cd frontend && npm run i18n:generate-hash && npm run test:changedsince
