name: Jest Coverage - changed files

on:
  pull_request:
    branches:
      - develop
      - main
      - release/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: git fetch origin ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: cd frontend && npm install -g yarn && yarn

      # - run: |
      #     git checkout -b develop origin/develop
      #     git checkout -
      # - name: Install dependencies
      #   run: cd frontend && yarn install

      - name: npm run test:changedsince
        run: cd frontend && npm run i18n:generate-hash && npm run test:changedsince
