name: Deploy coverage report to Pages

on:
  push:
    branches:
      - SIG-583

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: cd frontend && npm install -g yarn && yarn
      - run: yarn
      - run: |
          cd frontend 
          npm run i18n:generate-hash
          npm run test --silent || true
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./frontend/coverage"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
