name: validate
on: pull_request

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
      - name: Use Node v12.22
        uses: actions/setup-node@v2
        with:
          node-version: 12.22
      - name: ESLint
        run: yarn run lint
      - name: Build - Webpack
        run: yarn run build
