name: validate
on: pull_request

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
      - name: Use Node v12.22
        uses: actions/setup-node@v2
        with:
          node-version: 12.22
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
        working-directory: ./frontend
      - name: ESLint
        run: yarn run lint
        working-directory: ./frontend
      - name: Build - Webpack
        run: yarn run build
        working-directory: ./frontend
