name: Validate
on:
  pull_request:
    paths:
      - "pkg/**"
      - "frontend/**"

jobs:
  get_filters:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      query-service: ${{ steps.filter.outputs.query-service }}
      flattener: ${{ steps.filter.outputs.flattener }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            query-service:
              - 'pkg/query-service/**'
            flattener:
              - 'pkg/processors/flattener/**'
  frontend:
    needs:
      - get_filters
    if: ${{ needs.get_filters.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
      - name: Use Node v12.22
        uses: actions/setup-node@v2
        with:
          node-version: 12.22
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
          working-directory: ./frontend
      - name: ESLint
        run: yarn run lint
        working-directory: ./frontend
      - name: TSC
        run: yarn tsc
        working-directory: ./frontend
      - name: Build - Webpack
        run: yarn run build
        working-directory: ./frontend
